from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://yard-visibility-na12.voc.qa-stage.p-44.com/auth/login")
    page.get_by_label("Email Address").click()
    page.get_by_label("Email Address").fill("stagemckeee@yopmail.com")
    page.get_by_label("Password").click()
    page.get_by_label("Password").fill("Admin@123")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("button", name="Gate").click()
    page.get_by_role("link", name="Console").click()
    page.locator("a").filter(has_text="Select Site & Gate").click()
    page.get_by_text("Choose Your Site").click()
    page.get_by_text("collegedale").click()
    page.get_by_text("Choose Your Gate").click()
    page.get_by_text("P2_MAIN").click()
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("button", name="Drop").click()
    page.get_by_text("Drop Hook").click()
    # page.locator("#mat-input-0").click()
    # page.locator("#mat-input-0").fill("hook001")
    # page.locator("#mat-input-1").click()
    # page.locator("#mat-input-1").fill("trahook001")
    # page.locator("span").filter(has_text="Choose Carrier").first.click()
    # page.get_by_text("abfs-abf").click()
    # page.get_by_text("Choose Type").click()
    # page.locator("form").get_by_title("TRAILER").click()
    # page.locator("#seal1_arrival").click()
    # page.locator("#seal1_arrival").fill("seaalhook1")
    # page.locator("#seal1_arrival").press("Tab")
    # page.locator("#seal2_arrival").fill("sealhook2")
    # page.locator("#cab_num_arrival").click()
    # page.locator("#cab_num_arrival").fill("chook")
    # page.locator("#driver_cell_arrival").click()
    # page.locator("#driver_cell_arrival").fill("1235699")
    # page.locator("#first_name").click()
    # page.locator("#first_name").fill("drop")
    # page.locator("#last_name").click()
    # page.locator("#last_name").click()
    # page.locator("#last_name").fill("hook")
    # page.locator("#driver_email_id").click()
    # page.locator("#driver_email_id").fill("drop@hook.in")
    # page.locator("#comments_arrival").click()
    # page.locator("#comments_arrival").fill("drop hook testing")
    # page.get_by_text("Choose Option").nth(3).click()
    page.get_by_text("Choose Option").nth(2).click()
    input = page.locator("//input[contains(@class,'multiselect-search-input ng-valid ng-touched ng-dirty')]").click()
    input.fill("PKP")
    page.locator("#gate-console-arrival").get_by_role("listitem").first.click()
    page.pause()

    # page.get_by_role("textbox", name="multiselect-search").fill("pk")
    # page.get_by_text("pk3001").click()
    # page.get_by_role("button", name="Arrival").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
